@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiY3VlbnRhZGVzb3BvcnRlYUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gVmVyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpc3MiOiJTZXJ2aWRvckZlaUpXVCIsImF1ZCI6IkNsaWVudGVzRmVpSldUIiwiaWF0IjoxNzc2NjQyMzgzLCJleHAiOjE3NzY2NDM1ODN9.s4z1j0kDrKkeySi3LXK9RYK2GDOunF03Q4ozEoeL968
### Obtener todos los productos
GET http://localhost:3000/api/productos
Authorization: Bearer {{ token }}

###

### Buscar productos (usa ?s=)
GET http://localhost:3000/api/productos?s=lap
Authorization: Bearer {{ token }}

###

### Obtener producto por id
GET http://localhost:3000/api/productos/1
Authorization: Bearer {{ token }}

###

### Crear producto
POST http://localhost:3000/api/productos
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "titulo": "Producto de prueba",
    "descripcion": "Descripción de prueba",
    "precio": 120.50,
    "archivoid": null
}

###

### Actualizar producto
PUT http://localhost:3000/api/productos/1
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "titulo": "Producto editado",
    "descripcion": "Nueva descripción",
    "precio": 150.00,
    "archivado": false,
    "archivoid": null
}

###

### Eliminar producto
DELETE http://localhost:3000/api/productos/1
Authorization: Bearer {{ token }}

###

### Asignar categoría a producto
POST http://localhost:3000/api/productos/1/categoria
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "categoriaid": 2
}

###

### Eliminar categoría de producto
DELETE http://localhost:3000/api/productos/1/categoria/2
Authorization: Bearer {{ token }}